version: '3'

services:
  db:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./dbdata:/var/lib/mysql
  
  nginx:
    image: nginx:1.19.10-alpine
    ports:
      - 8080:80
    volumes:
      - ./my-site:/usr/share/nginx/html