version: "3"

services:
  # localhost:3000
  app:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M

  # localhost:3306
  db:
    image: mysql:8.0.30-debian
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 5s
      start_period: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 1G