{
 "title": "Store API Dash",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requisições",
     "type": "stat",
     "gridPos": { "h": 5, "w": 15, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{uri!~\"/actuator.+\", status!~\"2.+\"}",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Saturação",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "uso de CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "targets": [
      { "expr": "process_cpu_usage", "legendFormat": "{{__name__}} | {{application}}" },
      { "expr": "system_cpu_usage", "legendFormat": "{{__name__}} | {{application}}" }
     ]
    },
    {
     "title": "uso de memória (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "targets": [
      {
       "expr": "sum by(__name__) (jvm_memory_used_bytes)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(__name__) (jvm_memory_max_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum by(application) (disk_total_bytes)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(application) (disk_free_bytes)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Latência",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "latência por método + uri",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 17, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(uri, method) (http_server_requests_seconds_max{uri!~\"/actuator.+\"})",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Erros",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "stat",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(uri, method, status) (http_server_requests_seconds_count{uri!~\"/actuator.+\", status!~\"2.+\"})",
       "legendFormat": "{{method}} {{uri}} - {{status}}"
      }
     ]
    }
   ]
  }
 ]
}