version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    extra_hosts:
       - "host.docker.internal:host-gateway"